### ISSUE TITLE
Targetcli crash on clearconfig

### ISSUE THREAD

**Issue by abbynormal** [open-iscsi/targetcli-fb#108] opened 2018-03-30 17:27 UTC
Targetcli crashes, fairly rarely, when do a clearconfig directly after opening it. This is on CentOS 7.4 running kernel version 4.14.5:

targetcli shell version 2.1.fb47
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/> clearconfig confirm=true
Traceback (most recent call last):
  File "/usr/bin/targetcli", line 5, in <module>
    pkg_resources.run_script('targetcli-fb==2.1.fb47', 'targetcli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/targetcli_fb-2.1.fb47-py2.7.egg/EGG-INFO/scripts/targetcli", line 121, in <module>
    
  File "/usr/lib/python2.7/site-packages/targetcli_fb-2.1.fb47-py2.7.egg/EGG-INFO/scripts/targetcli", line 111, in main
    
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 905, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 734, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 848, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 823, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "build/bdist.linux-x86_64/egg/targetcli/ui_root.py", line 154, in ui_command_clearconfig
  File "build/bdist.linux-x86_64/egg/rtslib_fb/root.py", line 213, in clear_existing
OSError: [Errno 39] Directory not empty: '/sys/kernel/config/target/core/rd_mcp_7'

**Comment by agrover** [comment] 2018-04-02 23:37
Any chance you know what remained in that directory?

rtslib/root.py line 213 was part of an attempted fix that then got another fix later. Maybe we want to just remove the bit at 213 in favor. @pkalever @maurizio-lombardi  any thoughts?

**Comment by pkalever** [comment] 2018-04-03 15:42
> Any chance you know what remained in that directory?

I don't recollect anything in that dir other than these:

$ ls /sys/kernel/config/target/core/rd_mcp_7/ -l
total 0
drwxr-xr-x. 8 root root    0 Apr  3 20:06 rd_block
-r--r--r--. 1 root root 4096 Apr  3 20:06 hba_info
-rw-r--r--. 1 root root 4096 Apr  3 20:06 hba_mode

> rtslib/root.py line 213 was part of an attempted fix that then got another fix later. Maybe we want to just remove the bit at 213 in favor. @pkalever @maurizio-lombardi any thoughts?

Yes we have fixed the problem of stale hba dir with https://github.com/open-iscsi/rtslib-fb/pull/118

@agrover, cleaning hba only dir in clear_existing seems to be helpful, instead of sending that to trash, should we ensure that there are no directories under hba_dir at line 212, something like:
```
for hba_dir in glob.glob("%s/core/*_*" % self.configfs_dir):
    if not next(os.walk(hba_dir))[1]:
        os.rmdir(hba_dir)                                       

```
@abbynormal,
Can you give us the output from '# ls /sys/kernel/config/target/core/rd_mcp_7/ -lR'
It will be even nice to know the reproducer i.e. steps used to create/delete the block.

Thanks!

**Comment by abbynormal** [comment] 2018-12-03 18:56
My apologies, I found out that the email on this account was an old email and I didn't get a notification for this issue. I haven't seen it in a while, I will post the results of the above command if it happens again. We can close this issue for now and I can reopen if I see it.
Thanks!

**Comment by maurizio-lombardi** [comment] 2018-12-05 10:41
Thanks for the update, I close this issue

**Closed by maurizio-lombardi** 2018-12-05 10:41 UTC
