### ISSUE TITLE
write-thru deactivated 

### ISSUE THREAD

**Issue by c00kie55** [open-iscsi/targetcli-fb#133] opened 2019-04-17 14:28 UTC
o- block ...................................................................................................... [Storage Objects: 1]
  o- Raid10_40tb ......................... [/dev/disk/by-id/scsi-3600062b20406930024476f7cb6df9aab (43.7TiB) write-thru deactivated]

is it possible to enable?

**Comment by gonzoleeman** [comment] 2019-04-17 22:26
It is not _activated_ until it is being used (i.e. as a LUN on some front-end)

**Comment by c00kie55** [comment] 2019-04-23 10:14
Ok thanks, that is what i was hopping for.

Sendt fra min iPhone

**Comment by vincele** [comment] 2023-03-14 09:44
I wondered the same, got to this issue, and can confirm, the `write-thru deactivated` changed to `write-thru activated` as soon as i created a lun linked to the device.

I think this issue can be closed as "not a bug".

**Comment by maurizio-lombardi** [comment] 2023-03-14 14:33
I close the issue

**Closed by maurizio-lombardi** 2023-03-14 14:33 UTC
